AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  fortniteStatistics:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 896
      Timeout: 3
      Role: 'arn:aws:iam::436267071693:role/fortnite-statistics-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /fortniteStatistics
            Method: ANY
